spring.application.name=CycleGo

spring.datasource.url=jdbc:postgresql://localhost:5432/cyclego_db
spring.datasource.username=demo_user
spring.datasource.password=demopass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Rutas a pg_dump y pg_restore (ajusta según tu servidor)
db.backup.pg_dump_path=/usr/bin/pg_dump
db.backup.pg_restore_path=/usr/bin/pg_restore

# Opcional: límites de subida de archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=8080
