spring.application.name=CycleGo

spring.datasource.url=jdbc:postgresql://postgres-db:5432/cyclego_db
spring.datasource.username=demo_user
spring.datasource.password=demopass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
